### ISSUE TITLE
Add API Version Handling

### ISSUE THREAD

**Issue by daniel-centore** [me-next/menext-backend#18]
Make all endpoints include an API version parameter (int) as the first one. The client will include which API version it is trying to use. If the server does not support this API version (_ie_ the client is too old) then it should error so the client knows to tell the user that an update is req'd.

**Comment by ConnorFoody** [comment]
Do we want to make api versions visible in the library?

**Comment by daniel-centore** [comment]
What do you mean by that?

**Comment by ConnorFoody** [comment]
Like do we want to make it clear to consumers that there are multiple api versions? We could do something like 

```apiV2.playSong(...) ```
or 
```api.playSongV2(...)```

or we could just always keep it as:

```api.playSong(...)```

so that the consumer doesn't need to worry about versioning. 

Do we want to add a call like "is api build supported" or do we only want to identify that we have an old api version when we go to call an expired function?

**Comment by ConnorFoody** [comment]
Also lets get this refactor in with #16 and #17

**Comment by daniel-centore** [comment]
An "is API build supported" might be a better idea, and just call it when the app is opened.

I'm also interested in figuring out how we intend to deal with the situation where the server is restarted (and possibly upgraded) mid-event.

**Comment by ConnorFoody** [comment]
I think we run into the [CAP theorum](https://dzone.com/articles/better-explaining-cap-theorem) here. We may want to just say that live updates are out of the scope of this project. 

If we want to do live updates we could do something like stop adding events to "old" servers to slowly migrate things over. 

We can think about other ideas if we really want to include this.

**Comment by daniel-centore** [comment]
I meant more in the sense that the app should restart elegantly. I think it's assumed that we won't bother restoring state, at least for now.

**Comment by ConnorFoody** [comment]
Maybe I am missing something. 

By "restarted" do you mean a failure happens and the server crashes, then we restart the program? Or do you mean we restart the program to do something like update the software?
