### ISSUE TITLE
encapsulate user permission data better

### ISSUE THREAD

**Issue by ConnorFoody** [me-next/menext-backend#2]
Potential enhancement, to provide better encapsulation

Instead of doing [this line](https://github.com/me-next/menext-backend/blob/master/party/party.go#L53) we can make functions for each permission (ie set / check). 

We can make these changes in [this file](https://github.com/me-next/menext-backend/blob/master/party/user.go) after we strip out the permission stuff. 

We probably want to look into doing metaprogramming for this since we will frequently be adding functions...

**Comment by daniel-centore** [comment]
What's wrong with just a single function and using constants for each of the permissions? It will likely make sending permission data over the network less verbose in the code.

**Comment by daniel-centore** [comment]
The current user should probably be global and each of those functions should default to the current user

**Comment by ConnorFoody** [comment]
> What's wrong with just a single function and using constants for each of the permissions? 

Nothing really. Functions give code completion. Using a single function w/ constants is obviously more flexible. I'm not sure that there are any significant tradeoffs, it may just be a style thing. 

> It will likely make sending permission data over the network less verbose in the code.

It's about the same in go, [see this commit](https://github.com/me-next/menext-backend/commit/1ea429186679be66a9cbc4fc7658956a830eb1a3) for the changes needed. 

> The current user should probably be global and each of those functions should default to the current user

What do you mean by "current user"?

**Comment by daniel-centore** [comment]
Sorry, I was thinking from the front-end perspective for that last comment. I've gotten used to php lol

**Comment by ConnorFoody** [comment]
Ok, lets just stick with a map for now.
