### ISSUE TITLE
Currently Playing in Pull

### ISSUE THREAD

**Issue by daniel-centore** [me-next/menext-backend#20]
Add the currently playing song information to the backend poll.

Should include the following information:

- **CurrentSong**: string
The unique id of the song which is currently playing
- **SongStartTimeMs**: long
The unix time in ms at which we began playing said song
- **SongStartPos**: double
The position within the song that we began listening at in seconds
- **ServerTimeMs**: long
The server unix time in ms
- **Volume**: double
The volume of the song on a scale from 0-1
- **Playing**: bool
Whether we are playing or paused

SongStartTimeMs, SongStartPos, and ServerTimeMs collectively allow us to determine the current song position and whether or not a seek has occurred without needing to explicitly maintain a separate "seek has occurred" variable, which could get complicatedish if more than one update has occurred since a client's last poll.

**Comment by ConnorFoody** [comment]
Why not just treat the seek like any other change? 

I think we should put off seek until later because getting it to work smoothly may be a nasty issue. We might want to look into running something like an NTP server to make sure that everything is synced up properly.

**Comment by daniel-centore** [comment]
We can't treat seek like any other change because we can't differentiate between a song having started and pulling the slider back to zero. Also, we want to make sure that the correct position shows up on the slider for people who have newly joined an event.

As for NTP, I've done the whole custom NTP server thing before. I think it's wayy overkill for this. Just drop the unix time into the server response and add half the time it took to ping the server to it.

**Comment by ConnorFoody** [comment]
Looked into the accuracy of NTP, you're right, using NTP is definitely overkill. The heuristic you suggested will probably be appropriate. 

OK, I think I may get what you are thinking here... 

When a user skips forwards, should we try to make it like the skip happened and propagated instantly, even if it didn't. For example: 

1. Follower A skips to 0:30
2. Request hits server 250 ms later, at 0:30.250
3. Owner pull request hits the server another 500 ms later
4. Owner gets pull response 250 ms after request hit the server

It sounds like you want the owner to start playing at 0:31 (or maybe 0:30.750 if you don't count the follower => server trip). This is as if the seek happened instantly, but the owner didn't get the update until the song had played for trip time + pull latency. 

Do we want this? Or do we want the owner to start playing at 0:30 even? Do we think this time delay is negligible? 

As an aside, we probably want the owner to have a higher poll rate than everyone else. We may want to poll rate to vary with activity...

Is there a reasonable upper bound we can get on the delay? How about a 95th or 99th percentile delay guess? I'd guess 500ms to 1 sec per leg of the trip. 

Are multiple intra-pull seek updates different than other kinds of intra-pull updates? (Also are we using poll and pull interchangeably?) What's the plan for this? Do we just invalidate or delay any actions until the user has the most recent update? Do we want to do something more sophisticated? @mluquette what do you think? 

Why do we need a special event for starting a new song? Like what's the practical difference for the music player between starting a new song and moving the slider back to 0:00? Why would there be any difference between people who just joined and people who have been in the event for a while?

**Comment by daniel-centore** [comment]
I think the host should start playing at 0:31 because it sticks with the idea that the server is always right and the clients are just approximating the server. I personally believe that anybody should be able to take over hosting, in principle, even if we don't actually implement it that way.

If we want we can implement the host seeking exactly to 0:30, so it never misses any of the song, while tolerating the bar being slightly off for some clients.

I like the idea of having host have a higher poll rate for the host.

Multiple intra-pull seek updates are not different than other kinds of intra-pull updates. Updates occur and then the clients switch to whatever the current state is when they pull. I think the server being right and the clients just pulling the latest data frequently should work fine for everything we're doing.

> Do we just invalidate or delay any actions until the user has the most recent update? 

I think this should be case-by-case depending on the action type. An intra-update skip should be invalidated, but not an intra-update song suggestion. Basically things which can make playback wonky should probably just be invalidated and the user will press the skip button again if it's still what they want after they've received the update.

> Why do we need a special event for starting a new song?

I think you misunderstood me. The point I'm making is that if all we store is `SongPos` without some other information (how many seeks have been made, the time the last seek was made, or something similar), then seeking back to the beginning of the song is indistinguishable from the state the song was already in, _ie_ SongPos=0. This is the state we began playback in. We don't want the server to be sending the _current_ time of the song because then it makes a mess out of seeking (_ie_ we don't want the client to seek slightly every time it receives an update).

> What's the practical difference for the music player between starting a new song and moving the slider back to 0:00?

The point is that the state is exactly the same so we can't tell whether or not a seek has occurred. Since we get the entire state with every poll, we will always be told that the slider was at 0, whether that's because that's where it was when the song started, that's where it was when we seeked, or if we seeked a 2nd time for that matter.

> Why would there be any difference between people who just joined and people who have been in the event for a while?

If the time at which the seek occurred is not stored, then a new person joining will not be able to derive the current position of the slider.

> Are we using poll and pull interchangeably?

I pull the data when I poll the server. They can oft be used interchangeably.

**Comment by ConnorFoody** [comment]
> I think the host should start playing at 0:31 because it sticks with the idea that the server is always right and the clients are just approximating the server.

OK, sounds good. 

> I like the idea of having host have a higher poll rate for the host.

@samueljohnston96 if you're working on permissions you might want to add this in somewhere.

> Basically things which can make playback wonky should probably just be invalidated and the user will press the skip button again if it's still what they want after they've received the update.

I agree, this makes sense. 

>  The point I'm making is that if all we store is SongPos without some other information (how many seeks have been made, the time the last seek was made, or something similar), then seeking back to the beginning of the song is indistinguishable from the state the song was already in, ie SongPos=0. 

I think we may be on the same page, but I'm not sure. Are you saying we need a way to see if we actually tried to seek, but storing just song pos isn't good enough because we could miss seeks? 

Why can't we just use a change counter like we do with other updates? What's the problem if we miss a seek but the state is still the same? 

Could you provide an example of a problem that would occur as a result of this? 

> We don't want the server to be sending the current time of the song because then it makes a mess out of seeking (ie we don't want the client to seek slightly every time it receives an update).

Yeah, that makes sense. We might want to "soften" up the client by not seeking if the user's time is within something like 2 seconds of the desired time.

**Comment by daniel-centore** [comment]
> I think we may be on the same page, but I'm not sure.

Nope, you don't seem to understand what I'm trying to get at. I'm not in a proper frame of mind to answer this right now (#stpatty). Will write full answer tomorrow.

> Any reason we shouldn't put off implementing this until much later?

Precisely because it's tricky, we should at least know how we intend to implement it so we don't design things in a manner which might conflict. We can put off actually implementing it.

**Comment by daniel-centore** [comment]
> Are you saying we need a way to see if we actually tried to seek, but storing just song pos isn't good enough because we could miss seeks?

Correct

> Why can't we just use a change counter like we do with other updates?

We can, but doing it that way leads to the problem where a newly joined client can't figure out what the current song position is, because it doesn't know _when_ we seeked to that position.

> What's the problem if we miss a seek but the state is still the same?

The server-side state is the same (seeked to 0) even though the song _is not actually at 0_ because, say, 2 minutes may have elapsed since the seek occurred. I don't want the server to maintain actual current song position because of the aforementioned problem where you suggested "soften"ing up the client. I am against softening the client because it adds complexity and corner cases when they aren't necessary.

> Could you provide an example of a problem that would occur as a result of this?

Assuming all we have is a song seek position, the song will either jump back to the start every time any update occurs or won't jump back to start if someone tries to seek to start after the song has begun.

Assume all we have is a change counter and a song seek position, say 0:45. A client joins 2 minutes later. The new client will show the song as being at 0:45 while everybody else shows it at 2:45.

Please provide the exact variable combination you are suggesting for further examples.

**Comment by ConnorFoody** [comment]
OK, I think I get it now. I was thinking that the server will try to track the owner play position. You're saying the server just stamps changes. The clients figure out the song position using song start (or seek) position and the time since the seek request hit the server. 

Your approach is better than trying to have the server track the owner's song position. 

> SongStartTimeMs, SongStartPos, and ServerTimeMs collectively allow us to determine the current song position and whether or not a seek has occurred without needing to explicitly maintain a separate "seek has occurred" variable, which could get complicatedish if more than one update has occurred since a client's last poll.

How would you avoid maintaining a "seek occurred" variable without adding more info to the pull request? Are you saying we put the "currently playing" info in each pull? If we invalidate all but the first seek in a poll window why would it be tricky to maintain a "seek occurred" variable?

**Comment by daniel-centore** [comment]
More than one update can occur between polls, so a boolean seek occurred variable would either always be true after the first seek, which doesn't tell us if subsequent seeks have occurred, or would become false with the first update after the seek, which might make a client miss the seek.

What we need is a seek counter, like we are using for the polling, but in practice we don't actually need one because we can use a change in `SongStartTimeMs` for the same purpose. We already need `SongStartTimeMs` so the client can derive the actual current song position.

**Comment by ConnorFoody** [comment]
Sorry, I said "seek occurred" but I meant seek counter. 

Are you saying we send ```SongStartTimeMs``` in each pull response, or receive it in each request? If the client only sends a change id and we don't expect the polling to be reliable then how can we decide if we need to send the client info without a change counter?

**Comment by daniel-centore** [comment]
We still have the same overall change counter, but we don't need a seek change counter.

We send `SongStartTimeMs` in each poll response. If it has changed, then a seek occurred and we derive the current song position. The variable might also be called `WhenSeekOccurredUnixTimeMs`.

**Comment by ConnorFoody** [comment]
Why send the ```SongStartTimeMs``` each time? What problem does that solve? Doesn't this break with the "only send changes" pull approach? 

Are you concerned that clients will drift away from the actual time?

**Comment by daniel-centore** [comment]
Not "each time" but rather "each time we send the state," _ie_ whenever any part of the state changes. In principle, we should be able to send all state every time we poll. The only reason we are not doing that is for performance. So, one could argue that we are "sending" it each time even if we don't _actually_ send it.

> Are you concerned that clients will drift away from the actual time?

No. Short term drift is negligible. Long term drift is corrected by NTP. Differences in time between phone and server (not drift, but still pertinent) are fixed by status updates which include the server's time.

**Comment by ConnorFoody** [comment]
Ok, so sequence looks like this: 

1. Someone seeks, hits server creating state change id 5. 
2. Clients poll the server with change id 4, get update which includes all the state. 
3. Clients check if a seek changed by comparing the new ```SongStartTimeMs``` with their old ```SongStartTimeMs``` and, as discussed above, seek to the new position. 
4. Clients poll the server with change id 5, get nothing back
5. Someone suggests a song, hits server creating change id 6
6. Clients poll, get state, compare ```SongStartTimeMs``` to existing, don't see any changes so they don't seek.

**Comment by daniel-centore** [comment]
Bingo
