### ISSUE TITLE
Securify Usernames

### ISSUE THREAD

**Issue by daniel-centore** [me-next/menext-backend#21]
When a user creates or joins an event, generate a random secure key and send it back to the user. All future requests to the event use this key instead of a username. This prevents most trivial privilege escalation.

**Comment by ConnorFoody** [comment]
Right now the user passes in a unique id and a "display name". If we can pull something like the mac address for the user ID can we just use that?

**Comment by daniel-centore** [comment]
Not exactly secure since any app on the phone can get it, and it's literally harder than just generating a random sequence of characters using a secure library.

**Comment by daniel-centore** [comment]
How everything works has changed significantly. No longer applicable.
