### ISSUE TITLE
Cleanup Dead Events

### ISSUE THREAD

**Issue by daniel-centore** [me-next/menext-backend#25]
Remove events without any activity for a few days

**Comment by ConnorFoody** [comment]
What counts as activity? Does a pull count?

**Comment by daniel-centore** [comment]
A change in the `change id` is activity

**Comment by ConnorFoody** [comment]
Took first stab at cleanup [here](https://github.com/me-next/menext-backend/blob/event-cleanup/server/partyManager.go#L101). 

This might cause a big pause, details are in the code. Do we want to worry about the performance here right now?

**Comment by ConnorFoody** [comment]
We might also want to look into removing parties that don't have any users, or somehow making sure users aren't in multiple parties.

**Comment by daniel-centore** [comment]
I'd rather avoid cron/external dependencies. Can't we do something using native golang? Are there no packages which provide cron-like behaviour?

> This might cause a big pause

It's O(n). I'm not concerned at all. We'd likely need a second server for a host of other reasons well before this pause would be intolerable, even calling this cleanup code every single poll.

**Comment by ConnorFoody** [comment]
Sorry, I should have just said "background job". This is all in the go std lib. I'll fix the comment in the code as well. 

The "chron job" bit is [here](https://github.com/me-next/menext-backend/blob/event-cleanup/server/partyManager.go#L27-L33). It's just a background worker that periodically calls the party/event manager cleanup function.
