### ISSUE TITLE
make mechanism for client pulls

### ISSUE THREAD

**Issue by ConnorFoody** [me-next/menext-backend#4]
How will users retrieve data from the backend?

**Comment by daniel-centore** [comment]
Backend never sends anything to the client _pe se_. It only respond to requests.

I propose one catchall RESTful command which is just "hey, anything new?" and then the backend will respond with permission changes, queue state, etc.

**Comment by ConnorFoody** [comment]
Yeah, you're right on the backend not sending. I'll improve the phrasing on this. 

I don't like one "is anything new" call because we would need to keep track of "new". I agree that we should have just one endpoint to get all the state.

**Comment by daniel-centore** [comment]
I was thinking more along the lines of attaching an id to each event and then having the clients request events > 327, for example. But now that I think about it, that's likely overkill and could introduce subtle bugs.

**Comment by ConnorFoody** [comment]
Yeah, aren't really concerned about performance for this application. 

Sounds like we are settled that we'll have 1 pull function that sends everything?

**Comment by daniel-centore** [comment]
I agree.

**Comment by ConnorFoody** [comment]
@daniel-centore I think this is closed?
