### ISSUE TITLE
Include user votes in pull

### ISSUE THREAD

**Issue by daniel-centore** [me-next/menext-backend#50]
In the output for the pull, within each suggested song it should output a user's vote for that song as `user_vote: VALUE` where the value is either `-1`, `0`, or `1`.

**Comment by ConnorFoody** [comment]
This code is already in, see [this line](https://github.com/me-next/menext-backend/blob/develop/party/votableQueue.go#L193). 

You can test it by suggesting a song and pulling. A "vote" field in the song indicates how the user voted.
